// Common disposable/temporary email domains to block at signup
// This is a curated subset; fakefilter package handles the full list server-side
const DISPOSABLE_DOMAINS = new Set([
  "mailinator.com","guerrillamail.com","guerrillamailblock.com","grr.la","guerrillamail.info",
  "guerrillamail.net","guerrillamail.org","guerrillamail.de","sharklasers.com","guerrilla.ml",
  "tempmail.com","temp-mail.org","temp-mail.io","throwaway.email","yopmail.com","yopmail.fr",
  "yopmail.net","dispostable.com","maildrop.cc","mailnesia.com","tempail.com","fakeinbox.com",
  "trashmail.com","trashmail.me","trashmail.net","trashymail.com","10minutemail.com",
  "10minutemail.net","minutemail.com","tempmailaddress.com","mohmal.com","emailondeck.com",
  "getairmail.com","mailcatch.com","mailexpire.com","mailmoat.com","mailnull.com",
  "mailsac.com","mailscrap.com","mailshell.com","mailsiphon.com","mailtemp.info",
  "mailzilla.com","nomail.xl.cx","throwam.com","tmpmail.net","tmpmail.org",
  "getnada.com","abyssmail.com","emkei.cz","zzz.com","spamgourmet.com",
  "bugmenot.com","mytemp.email","burner.kiwi","discard.email","discardmail.com",
  "discardmail.de","disposableaddress.com","disposeamail.com","dm.w3internet.co.uk",
  "e4ward.com","emailmiser.com","emailsensei.com","emailtemporario.com.br",
  "emailwarden.com","enterto.com","ephemail.net","etranquil.com","etranquil.net",
  "etranquil.org","evopo.com","explodemail.com","express.net.ua","extremail.ru",
  "fakedemail.com","filzmail.com","fixmail.tk","flyspam.com","frapmail.com",
  "front14.org","fux0ringduh.com","gishpuppy.com","great-host.in","harakirimail.com",
  "hartbot.de","hatespam.org","hellodream.mobi","hidemail.de","hidzz.com",
  "hotpop.com","ichimail.com","imails.info","inbax.tk","inbox.si",
  "incognitomail.com","incognitomail.net","incognitomail.org","insorg-mail.info",
  "ipoo.org","irish2me.com","jetable.com","jetable.fr.nf","jetable.net",
  "jetable.org","jnxjn.com","jourrapide.com","kasmail.com","kaspop.com",
  "keepmymail.com","killmail.com","killmail.net","klzlk.com","koszmail.pl",
  "kurzepost.de","lawlita.com","letthemeatspam.com","lhsdv.com","lifebyfood.com",
  "link2mail.net","litedrop.com","lol.ovpn.to","lookugly.com","lopl.co.cc",
  "lortemail.dk","lr78.com","maileater.com","mailexpire.com","mailforspam.com",
  "mailin8r.com","mailinator.net","mailinator2.com","mailincubator.com",
  "mailme.ir","mailme.lv","mailmetrash.com","mailquack.com","mailslapping.com",
  "meltmail.com","mezimages.net","mfsa.ru","mintemail.com","mjukgansen.com",
  "mobi.web.id","mobileninja.co.uk","moncourrier.fr.nf","monemail.fr.nf",
  "monmail.fr.nf","mt2015.com","mx0.wwwnew.eu","mypartyclip.de","myphantom.com",
  "mysamp.de","mytempemail.com","mytrashmail.com","nabala.com","neverbox.com",
  "nobulk.com","noclickemail.com","nogmailspam.info","nomail.xl.cx","nomail2me.com",
  "nospam.ze.tc","nospam4.us","nospamfor.us","nospammail.net","notmailinator.com",
  "nowmymail.com","nurfuerspam.de","nus.edu.sg","nwldx.com","objectmail.com",
  "obobbo.com","odnorazovoe.ru","oneoffemail.com","onewaymail.com","oopi.org",
  "ordinaryamerican.net","otherinbox.com","ourklips.com","outlawspam.com",
  "ovpn.to","owlpic.com","pancakemail.com","pjjkp.com","plexolan.de",
  "pookmail.com","privacy.net","proxymail.eu","prtnx.com","punkass.com",
  "putthisinyouremail.com","qq.com","quickinbox.com","rcpt.at","reallymymail.com",
  "receiveee.com","regbypass.com","rejectmail.com","rhyta.com","rklips.com",
  "rmqkr.net","royal.net","rppkn.com","rtrtr.com","s0ny.net","safe-mail.net",
  "safersignup.de","safetymail.info","safetypost.de","sandelf.de",
  "saynotospams.com","scatmail.com","schafmail.de","selfdestructingmail.com",
  "shiftmail.com","shitmail.me","shortmail.net","sibmail.com","skeefmail.com",
  "slaskpost.se","slipry.net","slopsbox.com","slowslow.de","smashmail.de",
  "smellfear.com","snakemail.com","sneakemail.com","sneakymail.de",
  "snkmail.com","sofort-mail.de","softpls.asia","sogetthis.com",
  "soodonims.com","spam.la","spam.su","spam4.me","spamavert.com",
  "spambob.com","spambob.net","spambob.org","spambog.com","spambog.de",
  "spambog.ru","spambox.info","spambox.irishspringrealty.com","spambox.us",
  "spamcannon.com","spamcannon.net","spamcero.com","spamcorptastic.com",
  "spamcowboy.com","spamcowboy.net","spamcowboy.org","spamday.com",
  "spamex.com","spamfighter.cf","spamfighter.ga","spamfighter.gq",
  "spamfighter.ml","spamfighter.tk","spamfree24.com","spamfree24.de",
  "spamfree24.eu","spamfree24.info","spamfree24.net","spamfree24.org",
  "spamgoes.in","spamherelots.com","spamhereplease.com","spamhole.com",
  "spamify.com","spaminator.de","spamkill.info","spaml.com","spaml.de",
  "spammotel.com","spamobox.com","spamoff.de","spamslicer.com",
  "spamspot.com","spamstack.net","spamthis.co.uk","spamtrap.ro",
  "spamtrail.com","spamwc.de","suremail.info","teleworm.us","thankyou2010.com",
  "thc.st","tittbit.in","tmails.net","toiea.com","trash-amil.com",
  "trash-mail.at","trash-mail.com","trash-mail.de","trash2009.com",
  "trash2010.com","trash2011.com","trashdevil.com","trashdevil.de",
  "trashemail.de","trashmail.at","trashmail.io","trashmail.org",
  "trashmailer.com","trashymail.net","turual.com","twinmail.de",
  "uggsrock.com","upliftnow.com","uplipht.com","venompen.com",
  "veryreallyslow.com","viditag.com","viewcastmedia.com",
  "viewcastmedia.net","viewcastmedia.org","vomoto.com","vpn.st",
  "vsimcard.com","vubby.com","wasteland.rfc822.org","webemail.me",
  "webm4il.info","wegwerfadresse.de","wegwerfmail.de","wegwerfmail.net",
  "wegwerfmail.org","wetrainbayarea.com","wetrainbayarea.org",
  "wh4f.org","whatiaas.com","whatpaas.com","whyspam.me","wickmail.net",
  "wilemail.com","willhackforfood.biz","willselfdestruct.com","winemaven.info",
  "wronghead.com","wuzup.net","wuzupmail.net","wwwnew.eu","xagloo.com",
  "xemaps.com","xents.com","xmaily.com","xoxy.net","yapped.net",
  "yep.it","yogamaven.com","yopmail.gq","ypmail.webarnak.fr.eu.org",
  "yuurok.com","zehnminutenmail.de","zippymail.info","zoaxe.com",
  "zoemail.org",
]);

// Patterns commonly found in disposable / throwaway / temp-mail providers.
const DISPOSABLE_PATTERNS = [
  /(^|\.)temp(mail|-mail|email|inbox)?\./,
  /(^|\.)trash(mail|email)?\./,
  /(^|\.)throw[-_]?away/,
  /(^|\.)disposable/,
  /(^|\.)fake[-_]?(mail|inbox)/,
  /(^|\.)burner/,
  /(^|\.)mailinator/,
  /(^|\.)guerrilla/,
  /(^|\.)yopmail/,
  /(^|\.)10minute/,
  /(^|\.)minutemail/,
  /(^|\.)spam(box|gourmet|fighter|free)/,
  /(^|\.)getnada/,
  /(^|\.)maildrop/,
  /(^|\.)mohmal/,
  /(^|\.)sharklasers/,
  /(^|\.)dispostable/,
  /\.tk$/,
  /\.ml$/,
  /\.ga$/,
  /\.cf$/,
  /\.gq$/,
];

export function isDisposableEmail(email: string): boolean {
  const domain = email.split("@")[1]?.toLowerCase().trim();
  if (!domain) return false;
  if (DISPOSABLE_DOMAINS.has(domain)) return true;
  // Match against parent domain too (e.g. foo.mailinator.com)
  const parts = domain.split(".");
  for (let i = 1; i < parts.length; i++) {
    const sub = parts.slice(i).join(".");
    if (DISPOSABLE_DOMAINS.has(sub)) return true;
  }
  return DISPOSABLE_PATTERNS.some((re) => re.test(domain));
}
