/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SellRouteImport } from './routes/sell'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReportRouteImport } from './routes/report'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PreferencesRouteImport } from './routes/preferences'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as KycRouteImport } from './routes/kyc'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as HelpRouteImport } from './routes/help'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopIdRouteImport } from './routes/shop.$id'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as PaymentReturnRouteImport } from './routes/payment.return'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'
import { Route as LegalDocRouteImport } from './routes/legal.$doc'
import { Route as InboxUserIdRouteImport } from './routes/inbox_.$userId'
import { Route as CheckoutProductIdRouteImport } from './routes/checkout.$productId'
import { Route as ApiReviewAppealRouteImport } from './routes/api/review-appeal'
import { Route as ApiModerateRouteImport } from './routes/api/moderate'
import { Route as ProductIdEditRouteImport } from './routes/product.$id_.edit'
import { Route as ApiPublicBootstrapAdminRouteImport } from './routes/api/public/bootstrap-admin'
import { Route as ApiPaystackVerifyRouteImport } from './routes/api/paystack.verify'
import { Route as ApiPaystackInitiateRouteImport } from './routes/api/paystack.initiate'
import { Route as ApiPaypalCaptureRouteImport } from './routes/api/paypal/capture'
import { Route as ApiPublicV1ProductsRouteImport } from './routes/api/public/v1/products'
import { Route as ApiPublicPaystackWebhookRouteImport } from './routes/api/public/paystack.webhook'
import { Route as ApiPublicPaypalWebhookRouteImport } from './routes/api/public/paypal/webhook'
import { Route as ApiPublicPaypalPollRouteImport } from './routes/api/public/paypal/poll'
import { Route as ApiPublicV1ProductsIdRouteImport } from './routes/api/public/v1/products.$id'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PreferencesRoute = PreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const KycRoute = KycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIdRoute = ShopIdRouteImport.update({
  id: '/shop/$id',
  path: '/shop/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentReturnRoute = PaymentReturnRouteImport.update({
  id: '/payment/return',
  path: '/payment/return',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OrdersRoute,
} as any)
const LegalDocRoute = LegalDocRouteImport.update({
  id: '/legal/$doc',
  path: '/legal/$doc',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxUserIdRoute = InboxUserIdRouteImport.update({
  id: '/inbox_/$userId',
  path: '/inbox/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutProductIdRoute = CheckoutProductIdRouteImport.update({
  id: '/checkout/$productId',
  path: '/checkout/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReviewAppealRoute = ApiReviewAppealRouteImport.update({
  id: '/api/review-appeal',
  path: '/api/review-appeal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiModerateRoute = ApiModerateRouteImport.update({
  id: '/api/moderate',
  path: '/api/moderate',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdEditRoute = ProductIdEditRouteImport.update({
  id: '/product/$id_/edit',
  path: '/product/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBootstrapAdminRoute = ApiPublicBootstrapAdminRouteImport.update({
  id: '/api/public/bootstrap-admin',
  path: '/api/public/bootstrap-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaystackVerifyRoute = ApiPaystackVerifyRouteImport.update({
  id: '/api/paystack/verify',
  path: '/api/paystack/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaystackInitiateRoute = ApiPaystackInitiateRouteImport.update({
  id: '/api/paystack/initiate',
  path: '/api/paystack/initiate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaypalCaptureRoute = ApiPaypalCaptureRouteImport.update({
  id: '/api/paypal/capture',
  path: '/api/paypal/capture',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1ProductsRoute = ApiPublicV1ProductsRouteImport.update({
  id: '/api/public/v1/products',
  path: '/api/public/v1/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaystackWebhookRoute =
  ApiPublicPaystackWebhookRouteImport.update({
    id: '/api/public/paystack/webhook',
    path: '/api/public/paystack/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaypalWebhookRoute = ApiPublicPaypalWebhookRouteImport.update({
  id: '/api/public/paypal/webhook',
  path: '/api/public/paypal/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaypalPollRoute = ApiPublicPaypalPollRouteImport.update({
  id: '/api/public/paypal/poll',
  path: '/api/public/paypal/poll',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1ProductsIdRoute = ApiPublicV1ProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiPublicV1ProductsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/help': typeof HelpRoute
  '/inbox': typeof InboxRoute
  '/invite': typeof InviteRoute
  '/kyc': typeof KycRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/orders': typeof OrdersRouteWithChildren
  '/payments': typeof PaymentsRoute
  '/preferences': typeof PreferencesRoute
  '/privacy': typeof PrivacyRoute
  '/report': typeof ReportRoute
  '/reset-password': typeof ResetPasswordRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/sell': typeof SellRoute
  '/settings': typeof SettingsRoute
  '/wallet': typeof WalletRoute
  '/api/moderate': typeof ApiModerateRoute
  '/api/review-appeal': typeof ApiReviewAppealRoute
  '/checkout/$productId': typeof CheckoutProductIdRoute
  '/inbox/$userId': typeof InboxUserIdRoute
  '/legal/$doc': typeof LegalDocRoute
  '/orders/$id': typeof OrdersIdRoute
  '/payment/return': typeof PaymentReturnRoute
  '/product/$id': typeof ProductIdRoute
  '/shop/$id': typeof ShopIdRoute
  '/api/paypal/capture': typeof ApiPaypalCaptureRoute
  '/api/paystack/initiate': typeof ApiPaystackInitiateRoute
  '/api/paystack/verify': typeof ApiPaystackVerifyRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
  '/product/$id/edit': typeof ProductIdEditRoute
  '/api/public/paypal/poll': typeof ApiPublicPaypalPollRoute
  '/api/public/paypal/webhook': typeof ApiPublicPaypalWebhookRoute
  '/api/public/paystack/webhook': typeof ApiPublicPaystackWebhookRoute
  '/api/public/v1/products': typeof ApiPublicV1ProductsRouteWithChildren
  '/api/public/v1/products/$id': typeof ApiPublicV1ProductsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/help': typeof HelpRoute
  '/inbox': typeof InboxRoute
  '/invite': typeof InviteRoute
  '/kyc': typeof KycRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/orders': typeof OrdersRouteWithChildren
  '/payments': typeof PaymentsRoute
  '/preferences': typeof PreferencesRoute
  '/privacy': typeof PrivacyRoute
  '/report': typeof ReportRoute
  '/reset-password': typeof ResetPasswordRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/sell': typeof SellRoute
  '/settings': typeof SettingsRoute
  '/wallet': typeof WalletRoute
  '/api/moderate': typeof ApiModerateRoute
  '/api/review-appeal': typeof ApiReviewAppealRoute
  '/checkout/$productId': typeof CheckoutProductIdRoute
  '/inbox/$userId': typeof InboxUserIdRoute
  '/legal/$doc': typeof LegalDocRoute
  '/orders/$id': typeof OrdersIdRoute
  '/payment/return': typeof PaymentReturnRoute
  '/product/$id': typeof ProductIdRoute
  '/shop/$id': typeof ShopIdRoute
  '/api/paypal/capture': typeof ApiPaypalCaptureRoute
  '/api/paystack/initiate': typeof ApiPaystackInitiateRoute
  '/api/paystack/verify': typeof ApiPaystackVerifyRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
  '/product/$id/edit': typeof ProductIdEditRoute
  '/api/public/paypal/poll': typeof ApiPublicPaypalPollRoute
  '/api/public/paypal/webhook': typeof ApiPublicPaypalWebhookRoute
  '/api/public/paystack/webhook': typeof ApiPublicPaystackWebhookRoute
  '/api/public/v1/products': typeof ApiPublicV1ProductsRouteWithChildren
  '/api/public/v1/products/$id': typeof ApiPublicV1ProductsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/help': typeof HelpRoute
  '/inbox': typeof InboxRoute
  '/invite': typeof InviteRoute
  '/kyc': typeof KycRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/orders': typeof OrdersRouteWithChildren
  '/payments': typeof PaymentsRoute
  '/preferences': typeof PreferencesRoute
  '/privacy': typeof PrivacyRoute
  '/report': typeof ReportRoute
  '/reset-password': typeof ResetPasswordRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/sell': typeof SellRoute
  '/settings': typeof SettingsRoute
  '/wallet': typeof WalletRoute
  '/api/moderate': typeof ApiModerateRoute
  '/api/review-appeal': typeof ApiReviewAppealRoute
  '/checkout/$productId': typeof CheckoutProductIdRoute
  '/inbox_/$userId': typeof InboxUserIdRoute
  '/legal/$doc': typeof LegalDocRoute
  '/orders/$id': typeof OrdersIdRoute
  '/payment/return': typeof PaymentReturnRoute
  '/product/$id': typeof ProductIdRoute
  '/shop/$id': typeof ShopIdRoute
  '/api/paypal/capture': typeof ApiPaypalCaptureRoute
  '/api/paystack/initiate': typeof ApiPaystackInitiateRoute
  '/api/paystack/verify': typeof ApiPaystackVerifyRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
  '/product/$id_/edit': typeof ProductIdEditRoute
  '/api/public/paypal/poll': typeof ApiPublicPaypalPollRoute
  '/api/public/paypal/webhook': typeof ApiPublicPaypalWebhookRoute
  '/api/public/paystack/webhook': typeof ApiPublicPaystackWebhookRoute
  '/api/public/v1/products': typeof ApiPublicV1ProductsRouteWithChildren
  '/api/public/v1/products/$id': typeof ApiPublicV1ProductsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/help'
    | '/inbox'
    | '/invite'
    | '/kyc'
    | '/notifications'
    | '/onboarding'
    | '/orders'
    | '/payments'
    | '/preferences'
    | '/privacy'
    | '/report'
    | '/reset-password'
    | '/saved'
    | '/search'
    | '/sell'
    | '/settings'
    | '/wallet'
    | '/api/moderate'
    | '/api/review-appeal'
    | '/checkout/$productId'
    | '/inbox/$userId'
    | '/legal/$doc'
    | '/orders/$id'
    | '/payment/return'
    | '/product/$id'
    | '/shop/$id'
    | '/api/paypal/capture'
    | '/api/paystack/initiate'
    | '/api/paystack/verify'
    | '/api/public/bootstrap-admin'
    | '/product/$id/edit'
    | '/api/public/paypal/poll'
    | '/api/public/paypal/webhook'
    | '/api/public/paystack/webhook'
    | '/api/public/v1/products'
    | '/api/public/v1/products/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/help'
    | '/inbox'
    | '/invite'
    | '/kyc'
    | '/notifications'
    | '/onboarding'
    | '/orders'
    | '/payments'
    | '/preferences'
    | '/privacy'
    | '/report'
    | '/reset-password'
    | '/saved'
    | '/search'
    | '/sell'
    | '/settings'
    | '/wallet'
    | '/api/moderate'
    | '/api/review-appeal'
    | '/checkout/$productId'
    | '/inbox/$userId'
    | '/legal/$doc'
    | '/orders/$id'
    | '/payment/return'
    | '/product/$id'
    | '/shop/$id'
    | '/api/paypal/capture'
    | '/api/paystack/initiate'
    | '/api/paystack/verify'
    | '/api/public/bootstrap-admin'
    | '/product/$id/edit'
    | '/api/public/paypal/poll'
    | '/api/public/paypal/webhook'
    | '/api/public/paystack/webhook'
    | '/api/public/v1/products'
    | '/api/public/v1/products/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/help'
    | '/inbox'
    | '/invite'
    | '/kyc'
    | '/notifications'
    | '/onboarding'
    | '/orders'
    | '/payments'
    | '/preferences'
    | '/privacy'
    | '/report'
    | '/reset-password'
    | '/saved'
    | '/search'
    | '/sell'
    | '/settings'
    | '/wallet'
    | '/api/moderate'
    | '/api/review-appeal'
    | '/checkout/$productId'
    | '/inbox_/$userId'
    | '/legal/$doc'
    | '/orders/$id'
    | '/payment/return'
    | '/product/$id'
    | '/shop/$id'
    | '/api/paypal/capture'
    | '/api/paystack/initiate'
    | '/api/paystack/verify'
    | '/api/public/bootstrap-admin'
    | '/product/$id_/edit'
    | '/api/public/paypal/poll'
    | '/api/public/paypal/webhook'
    | '/api/public/paystack/webhook'
    | '/api/public/v1/products'
    | '/api/public/v1/products/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  HelpRoute: typeof HelpRoute
  InboxRoute: typeof InboxRoute
  InviteRoute: typeof InviteRoute
  KycRoute: typeof KycRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  OrdersRoute: typeof OrdersRouteWithChildren
  PaymentsRoute: typeof PaymentsRoute
  PreferencesRoute: typeof PreferencesRoute
  PrivacyRoute: typeof PrivacyRoute
  ReportRoute: typeof ReportRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SavedRoute: typeof SavedRoute
  SearchRoute: typeof SearchRoute
  SellRoute: typeof SellRoute
  SettingsRoute: typeof SettingsRoute
  WalletRoute: typeof WalletRoute
  ApiModerateRoute: typeof ApiModerateRoute
  ApiReviewAppealRoute: typeof ApiReviewAppealRoute
  CheckoutProductIdRoute: typeof CheckoutProductIdRoute
  InboxUserIdRoute: typeof InboxUserIdRoute
  LegalDocRoute: typeof LegalDocRoute
  PaymentReturnRoute: typeof PaymentReturnRoute
  ProductIdRoute: typeof ProductIdRoute
  ShopIdRoute: typeof ShopIdRoute
  ApiPaypalCaptureRoute: typeof ApiPaypalCaptureRoute
  ApiPaystackInitiateRoute: typeof ApiPaystackInitiateRoute
  ApiPaystackVerifyRoute: typeof ApiPaystackVerifyRoute
  ApiPublicBootstrapAdminRoute: typeof ApiPublicBootstrapAdminRoute
  ProductIdEditRoute: typeof ProductIdEditRoute
  ApiPublicPaypalPollRoute: typeof ApiPublicPaypalPollRoute
  ApiPublicPaypalWebhookRoute: typeof ApiPublicPaypalWebhookRoute
  ApiPublicPaystackWebhookRoute: typeof ApiPublicPaystackWebhookRoute
  ApiPublicV1ProductsRoute: typeof ApiPublicV1ProductsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preferences': {
      id: '/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof PreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kyc': {
      id: '/kyc'
      path: '/kyc'
      fullPath: '/kyc'
      preLoaderRoute: typeof KycRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$id': {
      id: '/shop/$id'
      path: '/shop/$id'
      fullPath: '/shop/$id'
      preLoaderRoute: typeof ShopIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/return': {
      id: '/payment/return'
      path: '/payment/return'
      fullPath: '/payment/return'
      preLoaderRoute: typeof PaymentReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/legal/$doc': {
      id: '/legal/$doc'
      path: '/legal/$doc'
      fullPath: '/legal/$doc'
      preLoaderRoute: typeof LegalDocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox_/$userId': {
      id: '/inbox_/$userId'
      path: '/inbox/$userId'
      fullPath: '/inbox/$userId'
      preLoaderRoute: typeof InboxUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$productId': {
      id: '/checkout/$productId'
      path: '/checkout/$productId'
      fullPath: '/checkout/$productId'
      preLoaderRoute: typeof CheckoutProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/review-appeal': {
      id: '/api/review-appeal'
      path: '/api/review-appeal'
      fullPath: '/api/review-appeal'
      preLoaderRoute: typeof ApiReviewAppealRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/moderate': {
      id: '/api/moderate'
      path: '/api/moderate'
      fullPath: '/api/moderate'
      preLoaderRoute: typeof ApiModerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id_/edit': {
      id: '/product/$id_/edit'
      path: '/product/$id/edit'
      fullPath: '/product/$id/edit'
      preLoaderRoute: typeof ProductIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bootstrap-admin': {
      id: '/api/public/bootstrap-admin'
      path: '/api/public/bootstrap-admin'
      fullPath: '/api/public/bootstrap-admin'
      preLoaderRoute: typeof ApiPublicBootstrapAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paystack/verify': {
      id: '/api/paystack/verify'
      path: '/api/paystack/verify'
      fullPath: '/api/paystack/verify'
      preLoaderRoute: typeof ApiPaystackVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paystack/initiate': {
      id: '/api/paystack/initiate'
      path: '/api/paystack/initiate'
      fullPath: '/api/paystack/initiate'
      preLoaderRoute: typeof ApiPaystackInitiateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paypal/capture': {
      id: '/api/paypal/capture'
      path: '/api/paypal/capture'
      fullPath: '/api/paypal/capture'
      preLoaderRoute: typeof ApiPaypalCaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/products': {
      id: '/api/public/v1/products'
      path: '/api/public/v1/products'
      fullPath: '/api/public/v1/products'
      preLoaderRoute: typeof ApiPublicV1ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/paystack/webhook': {
      id: '/api/public/paystack/webhook'
      path: '/api/public/paystack/webhook'
      fullPath: '/api/public/paystack/webhook'
      preLoaderRoute: typeof ApiPublicPaystackWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/paypal/webhook': {
      id: '/api/public/paypal/webhook'
      path: '/api/public/paypal/webhook'
      fullPath: '/api/public/paypal/webhook'
      preLoaderRoute: typeof ApiPublicPaypalWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/paypal/poll': {
      id: '/api/public/paypal/poll'
      path: '/api/public/paypal/poll'
      fullPath: '/api/public/paypal/poll'
      preLoaderRoute: typeof ApiPublicPaypalPollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/products/$id': {
      id: '/api/public/v1/products/$id'
      path: '/$id'
      fullPath: '/api/public/v1/products/$id'
      preLoaderRoute: typeof ApiPublicV1ProductsIdRouteImport
      parentRoute: typeof ApiPublicV1ProductsRoute
    }
  }
}

interface OrdersRouteChildren {
  OrdersIdRoute: typeof OrdersIdRoute
}

const OrdersRouteChildren: OrdersRouteChildren = {
  OrdersIdRoute: OrdersIdRoute,
}

const OrdersRouteWithChildren =
  OrdersRoute._addFileChildren(OrdersRouteChildren)

interface ApiPublicV1ProductsRouteChildren {
  ApiPublicV1ProductsIdRoute: typeof ApiPublicV1ProductsIdRoute
}

const ApiPublicV1ProductsRouteChildren: ApiPublicV1ProductsRouteChildren = {
  ApiPublicV1ProductsIdRoute: ApiPublicV1ProductsIdRoute,
}

const ApiPublicV1ProductsRouteWithChildren =
  ApiPublicV1ProductsRoute._addFileChildren(ApiPublicV1ProductsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  HelpRoute: HelpRoute,
  InboxRoute: InboxRoute,
  InviteRoute: InviteRoute,
  KycRoute: KycRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  OrdersRoute: OrdersRouteWithChildren,
  PaymentsRoute: PaymentsRoute,
  PreferencesRoute: PreferencesRoute,
  PrivacyRoute: PrivacyRoute,
  ReportRoute: ReportRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SavedRoute: SavedRoute,
  SearchRoute: SearchRoute,
  SellRoute: SellRoute,
  SettingsRoute: SettingsRoute,
  WalletRoute: WalletRoute,
  ApiModerateRoute: ApiModerateRoute,
  ApiReviewAppealRoute: ApiReviewAppealRoute,
  CheckoutProductIdRoute: CheckoutProductIdRoute,
  InboxUserIdRoute: InboxUserIdRoute,
  LegalDocRoute: LegalDocRoute,
  PaymentReturnRoute: PaymentReturnRoute,
  ProductIdRoute: ProductIdRoute,
  ShopIdRoute: ShopIdRoute,
  ApiPaypalCaptureRoute: ApiPaypalCaptureRoute,
  ApiPaystackInitiateRoute: ApiPaystackInitiateRoute,
  ApiPaystackVerifyRoute: ApiPaystackVerifyRoute,
  ApiPublicBootstrapAdminRoute: ApiPublicBootstrapAdminRoute,
  ProductIdEditRoute: ProductIdEditRoute,
  ApiPublicPaypalPollRoute: ApiPublicPaypalPollRoute,
  ApiPublicPaypalWebhookRoute: ApiPublicPaypalWebhookRoute,
  ApiPublicPaystackWebhookRoute: ApiPublicPaystackWebhookRoute,
  ApiPublicV1ProductsRoute: ApiPublicV1ProductsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
